### ISSUE TITLE
About ComputeJacobian

### ISSUE THREAD

**Issue by yanqswhu** [izhengfan/ba_demo_ceres#2]
I am wondering about the following codes:
```
template<>
bool PoseSE3Parameterization<6>::ComputeJacobian(const double *x, double *jacobian) const
{
    Eigen::Map<Eigen::Matrix<double, 6, 6, Eigen::RowMajor> > J(jacobian);
    J.setIdentity();
    return true;
}
```
Why we need them?

**Comment by izhengfan** [comment]
This is a hack. Please read the 'Jacobians' section in README.

**Comment by izhengfan** [comment]
There is only one problem about this hack. For any other self-defined Residuals, you need to use the same hack.
