### ISSUE TITLE
Question about Jacobians

### ISSUE THREAD

**Issue by Gatsby23** [izhengfan/ba_demo_ceres#5]
```
template<>
bool PoseSE3Parameterization<7>::ComputeJacobian(const double *x, double *jacobian) const
{
    Eigen::Map<Eigen::Matrix<double, 7, 6, Eigen::RowMajor> > J(jacobian);
    J.setZero();
    J.block<6,6>(0, 0).setIdentity();
    return true;
}

```
I'm sorry to bothering you about the jacobians again, I have noticed that in PoseSE3Parameterization, the Jacobian is set to a 7*6 Identity Matrix. I'm wordering that that is to tell ceres there are only 6 parameters are need to modify in optimization, am I right？

**Comment by izhengfan** [comment]
I think the **Jacobians** section in README has explained it.
