### ISSUE TITLE
jacoboi error ?

### ISSUE THREAD

**Issue by chennuo0125-HIT** [izhengfan/ba_demo_ceres#7]
https://github.com/izhengfan/ba_demo_ceres/blob/c89b27f6c99b207ae3bf99e8fd992290a253da7a/parametersse3.cpp#L28
above line should be:
```
J_se3.block<2,3>(0,0) = - J_cam * quaterd.toRotationMatrix() * skew(point); 
```
or 
```
J_se3.block<2,3>(0,0) = - J_cam * skew(quaterd * point); 
```

**Comment by GDTR12** [comment]
I found this too, skew(p) should be changed to this: $`\boxed{\mathbf{\frac{\partial q\otimes a\otimes q^*}{\partial q}}=2[w\mathbf a+\mathbf{v\times a}\quad|\quad\mathbf{v^\top aI_3+va^\top- a v^\top}-w [\mathbf a]_\times]}\tag{174}`$

**Comment by izhengfan** [comment]
The **Jacobians** section in README has explained this
